### ISSUE TITLE
[Feature Request] .Net 8 support

### ISSUE THREAD

**Issue by jeroenhabets** [cristipufu/aspnetcore-redis-rate-limiting#105]
Hi @cristipufu,

My team is preparing to upgrade from .Net6 to .Net8 (due for GA in November) and I noticed this library is .Net7 only. Do you have any plans to add .Net8 support soon?

If not, is there anything holding you back where perhaps we could be of help?

Cheers, Jeroen

**Comment by cristipufu** [comment]
Hi @jeroenhabets, 

Yes, we'll release a new .NET 8 version as soon as it's GA (same day, pinky promise)

**Comment by cristipufu** [comment]
Ref: https://github.com/cristipufu/aspnetcore-redis-rate-limiting/pull/106

**Comment by cristipufu** [comment]
https://www.nuget.org/packages/RedisRateLimiting.AspNetCore/1.1.0
https://www.nuget.org/packages/RedisRateLimiting/1.1.0
