### ISSUE TITLE
ClientIdRateLimiterPolicy sample never returns 429

### ISSUE THREAD

**Issue by colbroth** [cristipufu/aspnetcore-redis-rate-limiting#158]
Issued the GET /clients several times and never receive a 429 response. This endpoint is using the ClientIdRateLimiterPolicy. I thought it could be because the swagger did not send the X-ClientId header so I added code to set clientId to "unknown" to test that theory. I also see that it is able to connect to azure redis because I see the key using redis cli. 
Is this endpoint suppose to issue a 429 response when several requests are made one after another? I hit the submit several times and never see the 429 response. I do get a 429 response for the endpoint GET /FixedWindow

**Comment by cristipufu** [comment]
The rate limits for the clients sample are stored in a local database: https://github.com/cristipufu/aspnetcore-redis-rate-limiting/blob/master/test/RedisRateLimiting.Sample.AspNetCore/Database/SampleDbContext.cs#L48

You need to use one of these identifiers:
```C#
modelBuilder.Entity<Client>().HasData(
                new Client
                {
                    Id = 1,
                    RateLimitId = 1,
                    Identifier = "client1",
                },
                new Client
                {
                    Id = 2,
                    RateLimitId = 2,
                    Identifier = "client2",
                },
                new Client
                {
                    Id = 3,
                    RateLimitId = 3,
                    Identifier = "client3",
                });
```
