### ISSUE TITLE
Implement RateLimiter.GetStatistics()

### ISSUE THREAD

**Issue by cristipufu** [cristipufu/aspnetcore-redis-rate-limiting#6]
```C#
public override RateLimiterStatistics? GetStatistics()
{
    throw new NotImplementedException();
}
```

**Comment by cristipufu** [comment]
Implemented for Concurrency Rate Limiter: ba9d9b79b6c3535937ec59f18980edf649d9fda4

**Comment by kamilslusarczyk** [comment]
Have you reopened this issue due to problems with merged PR's code?

**Comment by cristipufu** [comment]
> Have you reopened this issue due to problems with merged PR's code?

There are other strategies which don't have it implemented
