### ISSUE TITLE
RedisSlidingWindowRateLimiter breaks if configured with sub-second precision Window

### ISSUE THREAD

**Issue by hacst** [cristipufu/aspnetcore-redis-rate-limiting#62]
`RedisSlidingWindowManager` uses the [`EXPIREAT`](https://redis.io/commands/expireat/) redis call to update the expiry every time it attempts to acquire a lease. This function only accepts a whole number of seconds as its argument. However the expression `(RedisValue)_options.Window.TotalSeconds,` is used when passing the window size into the lua script where `TotalSeconds` is a double.

This usually works because `RedisValue` turns double into an integer if it can be exactly represented. But if a window size with sub-second precision is specified, the value is passed as a double and an error occurs.

The obvious fix is to just cast total seconds to `long` to truncate it before conversion to a RedisValue. Alternatively if sub-second precision is actually wanted Redis also supports millisecond precision for expiry through [`PEXPIREAT`](https://redis.io/commands/pexpireat/) since version 2.6.0.

If I know which option is preferred I can create a PR.

**Comment by cristipufu** [comment]
Maybe something like this? https://github.com/cristipufu/aspnetcore-redis-rate-limiting/pull/47

Feel free to open PRs
